[tool.poetry]
name = "education-backend"
version = "2022.10.31"
description = ""
authors = ["f213 <f@f213.in>"]
readme = "README.md"
packages = [{include = "education_backend"}]

[tool.poetry.dependencies]
python = "^3.11"
babel = "^2.12.1"
bcrypt = "^4.0.1"
bleach = "^6.0.0"
boto3 = "^1.28.48"
celery = "^5.3.4"
cmarkgfm = "^2022.10.27"
django = "^4.2.5"
djangorestframework = "^3.14.0"
django-anymail = "^10.1"
django-axes = "^6.1.1"
django-behaviors = "^0.5.1"
django-cachalot = "^2.6.1"
django-cors-headers = "^4.2.0"
django-debug-toolbar = "^4.2.0"
django-environ = "^0.11.2"
django-filter = "^23.2"
django-healthchecks = "^1.5.0"
django-ipware = "^5.0.0"
django-prettyjson = "^0.4.1"
django-split-settings = "^1.2.0"
django-storages = "^1.14"
django-tree-queries = "^0.15.0"
dj-rest-auth = "^5.0.0"
drf-jwt = "^1.19.2"
drf-recaptcha = "^3.0.0"
drf-spectacular = {extras = ["sidecar"], version = "^0.26.4"}
emoji = "^2.8.0"
httpx = {extras = ["http2"], version = "^0.25.0"}
pillow = "^10.0.1"
psycopg2-binary = "^2.9.7"
redis = "^5.0.0"
retry = "^0.9.2"
sentry-sdk = "^1.31.0"
shortuuid = "^1.0.11"
simplejson = "^3.19.1"
stripe = "^6.5.0"
whitenoise = "^6.5.0"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.2.1"
black = "^23.9.1"

flake8-absolute-import = "^1.0.0.1"
flake8-black = "^0.3.6"
flake8-bugbear = "^23.7.10"
flake8-cognitive-complexity = "^0.1.0"
flake8-django = "^1.4"
flake8-eradicate = "^1.5.0"
flake8-fixme = "^1.1.1"
flake8-isort = "^6.0.0"
flake8-multiline-containers = "^0.0.19"
flake8-mutable = "^1.2.0"
flake8-pep3101 = "^2.0.0"
flake8-pie = "^0.16.0"
flake8-print = "^5.0.0"
flake8-printf-formatting = "^1.1.2"
flake8-pyproject = "^1.2.3"
flake8-pytest = "^1.4"
flake8-pytest-style = "^1.7.2"
flake8-simplify = "^0.20.0"
flake8-tidy-imports = "^4.10.0"
flake8-todo = "^0.7"
flake8-use-fstring = "^1.4"
flake8-variables-names = "^0.0.6"
flake8-walrus = "^1.2.0"

freezegun = "^1.2.2"
ipython = "^8.15.0"
jedi = "^0.19.0"
mixer = "^7.2.2"
mypy = "^1.5.1"
pytest-django = "^4.5.2"
pytest-cov = "^4.1.0"
pytest-deadfixtures = "^2.2.1"
pytest-env = "^1.0.1"
pytest-freezegun = "^0.4.2"
pytest-mock = "^3.11.1"
pytest-randomly = "^3.15.0"
pytest-repeat = "^0.9.1"
pytest-xdist = "^3.3.1"
requests-mock = "^1.11.0"
respx = "^0.20.2"

boto3-stubs = "^1.28.48"
djangorestframework-stubs = "^3.14.2"
django-stubs = "^4.2.4"
types-babel = "^2.11.0.15"
types-bleach = "^6.0.0.4"
types-freezegun = "^1.1.10"
types-markdown = "^3.4.2.10"
types-pillow = "^10.0.0.3"
types-requests = "^2.31.0.2"
types-retry = "^0.9.9.4"
types-simplejson = "^3.19.0.2"
types-stripe = "^3.5.2.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
